### ISSUE TITLE
Black formatting

### ISSUE THREAD

**Issue by marcus7070** [CadQuery/cadquery-plugins#11]
Do we want to do black formatting on this repo? Could be through Actions on PRs, or could just be us manually running black whenever we feel motivated.

**Comment by jmwright** [comment]
> Do we want to do black formatting on this repo?

Yes, we probably should. I think doing it through GitHub Actions would be good. I know it's annoying to get a PR kicked just for formatting, but it helps keep the code base clean in the long term. Do you want to add it or should I?

**Comment by jmwright** [comment]
@marcus7070 I figured you were done for the day, so I added the black check. It's available in master. Feel free to adjust as needed.
