### ISSUE TITLE
Lint Check Does Not Run Properly On Forks

### ISSUE THREAD

**Issue by jmwright** [CadQuery/cadquery-plugins#14]
When run against a fork, the lint check will show a failure even when the check passes. The problem is not straight forward for the original Action dev to fix though.

References:
* Our comments on it: https://github.com/CadQuery/cadquery-plugins/pull/10#issuecomment-809106584
* The Action developer's open issue: https://github.com/wearerequired/lint-action/issues/13

The PSF [created a black Action](https://github.com/psf/black/pull/1421), but it doesn't seem to really be documented and I'm thinking it would suffer from the same bug of not working on forks since it's due to lacking functionality on GitHub's side.

I could also just try running black manually in our lint check Action.

**Comment by marcus7070** [comment]
Closed in #22 (unless we want some of the fancy annotations or other features that #22 doesn't do).

Here is correct [clean run](https://github.com/CadQuery/cadquery-plugins/runs/2475252958?check_suite_focus=true) and [dirty run](https://github.com/CadQuery/cadquery-plugins/pull/19/checks?check_run_id=2475310675).

**Comment by jmwright** [comment]
Thanks @marcus7070
